spring:
  application:
    name: webrtc
  security:
    jwt:
      secret: "kIx7TQ5yKpVtxgpI4KQ9zJxEwl8VVWH8KR9aQn8bE3o="

  datasource:
    url: jdbc:postgresql://localhost:5432/webrtc
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

sfu:
  base-url: http://localhost:8090
